language: node_js
node_js:
  - "12.14.0"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  - npm run build
after_script:
  # Sending build context
  - cp deploy/nginx.conf dist/nginx.conf
  - cp deploy/Dockerfile dist/Dockerfile
  - cd dist
  - docker build -t dd-web .
  - rm -rf dist/nginx.conf
  - rm -rf dist/Dockerfile
  - docker save dd-web:latest | gzip > dd-web.tar.gz
  - ls -a
