language: node_js
node_js:
  - "12.14.0"
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - sshpass
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  - npm run build
after_success:
  - cp deploy/nginx.conf dist/nginx.conf
  - cp deploy/Dockerfile dist/Dockerfile
  - sshpass -p "raspberry" scp -P 6000 -r ./dist pi@47.75.55.94:/home/pi/docker
