language: node_js
node_js:
  - "12.14.0"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  - npm run build
after_script:
  # Sending build context
  - cp deploy/nginx.conf dist/nginx.conf
  - cp deploy/Dockerfile dist/Dockerfile
  - cd dist
  - sshpass -p "$SSH_PWD" scp -P 6000 -r ./dist pi@47.75.55.94:/home/pi/docker
  - ls -a
