language: node_js
node_js:
  - "12.14.0"
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - sshpass
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  - npm run build
after_success:
  - cp deploy/nginx.conf dist/nginx.conf
  - cp deploy/Dockerfile dist/Dockerfile
  - sshpass -p "$SSH_PWD" scp -P $SSH_PORT -o stricthostkeychecking=no -r ./dist $SSH_USER@$SSH_HOST:$SSH_PATH
