language: node_js
node_js:
  - "12.14.0"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  - npm run build
after_script:
  - cp deploy/nginx.conf dist/nginx.conf
  - cp deploy/Dockerfile dist/Dockerfile
  - cd dist
  - docker build -t dd-web .
  - docker save -o dd-web.tar dd-web:latest
  - ls -a
